### ISSUE TITLE
Can't access the site ( https://mypdns.org/ )

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [mypdns/mypdns#2]
### Wildcard domain records

```CSV
.
```

### Screenshots

<details><summary>Screenshot</summary>

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Hi @AyanokojiK1yotaka 

that's is correct, as I no longer are hosting the Gitlab instance anymore, do to the electrical bill. This means I for know are using Github as the issue board.

When visiting https://mypdns.org/ you should be redirected here.
